title: Minimal theme
logo: 
description: Info about John Fricks
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
site.logo: false
title: Fricks Website
site.github.is_project_page: false
site.github.is_user_page: false