title: Minimal theme
site.logo: false
 title: Fricks Website
description: Info about John Fricks
show_downloads: false
site.github.is_project_page: true
site.github.is_user_page: false
google_analytics:
theme: jekyll-theme-minimal